build:
	gcc  BlCommands.c -o BlCommands.o
	gcc  BlReplyProcessing.c -o BlReplyProcessing.o
	gcc  fileops.c -o fileops.o
	gcc  LinuxSerialPort.c -o LinuxSerialPort.o
	gcc  OSxSerialPort.c -o OSxSerialPort.o
	gcc  utilities.c -o utilities.o
	gcc  WindowsSerialPort.c -o WindowsSerialPort.o
	gcc  main.c -o main.o
all: main.o BlCommands.o BlReplyProcessing.o fileops.o LinuxSerialPort.o
